### ISSUE TITLE
Joja Has Extra Stock - MFM was skipped by wrong dependencies

### ISSUE THREAD

**Issue by tomchang25** [LenneDalben/StardewValleyModsGPL#3]
In StardewValleyModsGPL/Joja Has Extra Stock/[MFM] Joja Has Extra Stock/manifest.json
	"Dependencies": [
		{
			"UniqueID": "LenneDalben.JojaMartExtraStock"
		}
	],

It seems to forget to be changed and can be solved by fixing like.
	"Dependencies": [
		{
			"UniqueID": "LenneDalben.JojaExtraStock"
		}
	],

**Comment by LenneDalben** [comment]
Thanks for reporting! I fixed it and updated the file [on ModDrop](https://www.moddrop.com/stardew-valley/mods/1033080-joja-has-extra-stock/notes).
